language: python # => 1
python: # => 2
  - "3.6"
services: # => 3
  - postgresql
env: # => 4
  -DJANGO=2.2.5 DB=postgresql
install: # => 5
  - (pip install -r requirements.txt)
before_script: # => 6
  - psql -c 'create database test;' -U postgres
script: # => 7
  - (python manage.py test)
  # - (python manage.py makemigrations)
  # - (python manage.py migrate)
  # - (python manage.py runserver)

deploy: # 9
  provider: heroku
  api_key: 3488bd7f-e6ea-4701-ade0-5e22f6f43f2f
  app: refill-api

notifications: # 10
  email:
    recipients:
      - deveidtolu18@gmail.com
    on_success: always # default: change
    on_failure: always # default: always