# Generated by Django 2.2.5 on 2020-03-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refill', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimepassword',
            name='expiry_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
