# Generated by Django 2.2.5 on 2020-03-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refill', '0002_auto_20200320_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimepassword',
            name='expiry_date',
            field=models.DateTimeField(),
        ),
    ]
