# Generated by Django 2.2.5 on 2020-03-20 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('refill', '0003_auto_20200320_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimepassword',
            name='phone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Field to save the phone number of the user.', max_length=15, null=True, unique=True, verbose_name='phone number'),
        ),
    ]
