# Generated by Django 2.2.5 on 2020-03-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refill', '0004_auto_20200320_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Field to save the phone number of the user.', max_length=15, null=True, verbose_name='phone number'),
        ),
    ]
