# Generated by Django 2.2.5 on 2020-03-21 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refill', '0005_auto_20200321_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onetimepassword',
            old_name='phone',
            new_name='phone_id',
        ),
    ]
