# Generated by Django 2.2.5 on 2020-03-23 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refill', '0007_auto_20200321_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='onetimepassword',
            name='used',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
